variable "region" {}
variable "cluster_code" {}
variable "cluster_version" {}
variable "master_ami" {}
variable "master_instance_type" {}
variable "master_volume_size" {}
variable "master_ip" {}
variable "master_subnet" {}
variable "node_ami" {}
variable "node_instance_type" {}
variable "node_volume_size" {}
variable "node_01_ip" {}
variable "node_02_ip" {}
variable "node_03_ip" {}
variable "node_subnet" {}
